version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"   # expose Flask app
    volumes:
      - ./logs:/var/log  # mount host ./logs directory so Promtail can read logs
    environment:
      - PYTHONUNBUFFERED=1   # ensure logs flush immediately

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./logs:/var/log   # match Flask log mount
    command: -config.file=/etc/promtail/config.yaml

volumes: {}
